/*
 June 20th, 2023
 Created by Derek Wang
 This form is an intro screen that is shown to the user when they open the game
 */


public class IntroScreen extends javax.swing.JFrame {

    /**
     * Creates new form IntroScreen
     */
    public IntroScreen() {
        initComponents();
        
        //Run innitGui to add text to screen
        initGui();
    }
    
    /*
    initGui
    
    This procedure updates the description text labels.
    
    Parameters: none
    
    Returns: none 
    */
    public void initGui()
    {
        //Set description text to html so it can be indented
        lblDesc.setText("<html>-The Original IQ test is a boardgame where the"
                + " objective is to remove all the pins from the board."
                + " In order to move a pin, that pin must 'hop' over another"
                + " pin to the next open spot.<br/>-The pin that was hopped over"
                + " is then removed from the board. You continute making moves"
                + " and removing pins until it is not possible to make</br>"
                + " any more moves.<br/> -A black circle means it is filled,"
                + " a white circle means it is empty.");
        lblDesc2.setText("<html>Now that we got the out of the way <br/>"
                + "Let's see how smart you are!");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTextBackground = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblDesc = new javax.swing.JLabel();
        lblGameIMG = new javax.swing.JLabel();
        lblCopyright = new javax.swing.JLabel();
        lblDesc2 = new javax.swing.JLabel();
        btnProceed = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlTextBackground.setBackground(new java.awt.Color(255, 255, 255));

        lblTitle.setFont(new java.awt.Font("Times New Roman", 1, 40)); // NOI18N
        lblTitle.setText("The Original IQ Test");

        lblDesc.setBackground(new java.awt.Color(255, 255, 255));
        lblDesc.setFont(new java.awt.Font("Yu Gothic Medium", 0, 16)); // NOI18N

        lblGameIMG.setFont(new java.awt.Font("Yu Gothic Medium", 0, 16)); // NOI18N
        lblGameIMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BoardGame.jpg"))); // NOI18N

        lblCopyright.setFont(new java.awt.Font("Yu Gothic Light", 0, 16)); // NOI18N
        lblCopyright.setText("WangBoardGames Enc.");

        lblDesc2.setBackground(new java.awt.Color(255, 255, 255));
        lblDesc2.setFont(new java.awt.Font("Yu Gothic Medium", 0, 20)); // NOI18N

        btnProceed.setFont(new java.awt.Font("Yu Gothic Medium", 0, 16)); // NOI18N
        btnProceed.setText("Proceed");
        btnProceed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProceedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTextBackgroundLayout = new javax.swing.GroupLayout(pnlTextBackground);
        pnlTextBackground.setLayout(pnlTextBackgroundLayout);
        pnlTextBackgroundLayout.setHorizontalGroup(
            pnlTextBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTextBackgroundLayout.createSequentialGroup()
                .addGroup(pnlTextBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTextBackgroundLayout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(lblTitle)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTextBackgroundLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTextBackgroundLayout.createSequentialGroup()
                        .addGroup(pnlTextBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlTextBackgroundLayout.createSequentialGroup()
                                .addGap(217, 217, 217)
                                .addComponent(btnProceed, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlTextBackgroundLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblGameIMG, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(pnlTextBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlTextBackgroundLayout.createSequentialGroup()
                                .addGap(0, 30, Short.MAX_VALUE)
                                .addComponent(lblCopyright))
                            .addComponent(lblDesc2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        pnlTextBackgroundLayout.setVerticalGroup(
            pnlTextBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTextBackgroundLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(lblDesc, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlTextBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTextBackgroundLayout.createSequentialGroup()
                        .addComponent(lblGameIMG, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTextBackgroundLayout.createSequentialGroup()
                        .addComponent(lblDesc2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)))
                .addGroup(pnlTextBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTextBackgroundLayout.createSequentialGroup()
                        .addComponent(btnProceed, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addComponent(lblCopyright, javax.swing.GroupLayout.Alignment.TRAILING)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(pnlTextBackground, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTextBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProceedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProceedActionPerformed
        //Dispose of frame when proceed button is pressed
        dispose();
    }//GEN-LAST:event_btnProceedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IntroScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IntroScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IntroScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IntroScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IntroScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProceed;
    private javax.swing.JLabel lblCopyright;
    private javax.swing.JLabel lblDesc;
    private javax.swing.JLabel lblDesc2;
    private javax.swing.JLabel lblGameIMG;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlTextBackground;
    // End of variables declaration//GEN-END:variables
}
